// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUuHmRX_T9oj6T_UTlDbxfMUMZbKqGeuk',
    appId: '1:208663714399:web:b28a347bbb4e695c4c99ea',
    messagingSenderId: '208663714399',
    projectId: 'productive-peers',
    authDomain: 'productive-peers.firebaseapp.com',
    storageBucket: 'productive-peers.firebasestorage.app',
    measurementId: 'G-9N85VK6GCC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbYy3ovNfUwlWT5lys8h8xJTGd8dZJqlY',
    appId: '1:208663714399:android:c8b80f48deb4e8384c99ea',
    messagingSenderId: '208663714399',
    projectId: 'productive-peers',
    storageBucket: 'productive-peers.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzA19DZhztiMV8s3vW63ju-OGG9DzUNBw',
    appId: '1:208663714399:ios:06619d99eeede18d4c99ea',
    messagingSenderId: '208663714399',
    projectId: 'productive-peers',
    storageBucket: 'productive-peers.firebasestorage.app',
    iosBundleId: 'com.example.productivePeers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzA19DZhztiMV8s3vW63ju-OGG9DzUNBw',
    appId: '1:208663714399:ios:06619d99eeede18d4c99ea',
    messagingSenderId: '208663714399',
    projectId: 'productive-peers',
    storageBucket: 'productive-peers.firebasestorage.app',
    iosBundleId: 'com.example.productivePeers',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUuHmRX_T9oj6T_UTlDbxfMUMZbKqGeuk',
    appId: '1:208663714399:web:648e7b8fd1bc95184c99ea',
    messagingSenderId: '208663714399',
    projectId: 'productive-peers',
    authDomain: 'productive-peers.firebaseapp.com',
    storageBucket: 'productive-peers.firebasestorage.app',
    measurementId: 'G-M2NLFLDLFQ',
  );
}
